export const hotel = {
  id: 'suitesviena',
  name: 'Suites Viena',
  location: 'Plaza de España, Madrid',
  address: 'C/ Juan Álvarez Mendizábal, 17, 28008 Madrid',
  phone: '+34 917 583 605',
  whatsapp: '+34 671 613 939',
  email: 'reservas@suitesviena.es',

  rooms: [
    {
      id: 'viena-capellanes',
      name: 'Viena + Capellanes',
      slug: 'viena-capellanes',
      size: 61,
      height: 2.70,
      naturalLight: true,
      combinable: true,
      description: 'El espacio más amplio del hotel. Resultado de unir las salas Viena y Capellanes, ofrece una superficie diáfana de 11m de largo por 5,5m de ancho con luz natural.',
      badge: 'Más solicitada',
      image: '/assets/suitesviena/sala-viena-capellanes.jpg',
      layouts: [
        { type: 'imperial', label: 'Imperial', icon: 'imperial', max: 24 },
        { type: 'u',        label: 'En U',     icon: 'u',        max: 24 },
        { type: 'escuela',  label: 'Escuela',  icon: 'escuela',  max: 30 },
        { type: 'teatro',   label: 'Teatro',   icon: 'teatro',   max: 40 },
      ],
      pricing: {
        halfDay: 290,
        fullDay: 490,
        currency: '€',
      },
      amenities: ['wifi', 'proyector', 'pantalla', 'flipchart', 'agua', 'material'],
    },
    {
      id: 'viena',
      name: 'Sala Viena',
      slug: 'viena',
      size: 34,
      height: 2.70,
      naturalLight: true,
      combinable: true,
      description: 'Situada en la 1ª planta con luz natural. Diáfana y versátil, mide 6m de largo por 5,5m de ancho. Ideal para reuniones de equipo y presentaciones.',
      badge: null,
      image: '/assets/suitesviena/sala-viena.jpg',
      layouts: [
        { type: 'imperial', label: 'Imperial', icon: 'imperial', max: 18 },
        { type: 'u',        label: 'En U',     icon: 'u',        max: 15 },
        { type: 'escuela',  label: 'Escuela',  icon: 'escuela',  max: 18 },
        { type: 'teatro',   label: 'Teatro',   icon: 'teatro',   max: 30 },
      ],
      pricing: {
        halfDay: 190,
        fullDay: 320,
        currency: '€',
      },
      amenities: ['wifi', 'proyector', 'pantalla', 'flipchart', 'agua', 'material'],
    },
    {
      id: 'capellanes',
      name: 'Sala Capellanes',
      slug: 'capellanes',
      size: 27,
      height: 2.70,
      naturalLight: false,
      combinable: true,
      description: 'Sala íntima y funcional en la 1ª planta. Mide 4,9m de largo por 5,5m de ancho. Perfecta para reuniones pequeñas y sesiones de trabajo en grupo.',
      badge: null,
      image: '/assets/suitesviena/sala-capellanes.jpg',
      layouts: [
        { type: 'imperial', label: 'Imperial', icon: 'imperial', max: 12 },
        { type: 'u',        label: 'En U',     icon: 'u',        max: 12 },
        { type: 'escuela',  label: 'Escuela',  icon: 'escuela',  max: 12 },
        { type: 'teatro',   label: 'Teatro',   icon: 'teatro',   max: 20 },
      ],
      pricing: {
        halfDay: 150,
        fullDay: 250,
        currency: '€',
      },
      amenities: ['wifi', 'proyector', 'pantalla', 'flipchart', 'agua', 'material'],
    },
  ],

  extras: [
  // Coffee Breaks
  {
    id: 'coffee-dulce',
    category: 'coffee',
    name: 'Coffee Break Dulce',
    description: 'Café Colombia Natural, leche, infusiones, 2 bollería mini, 1 croissant mantequilla, 1 muffin, zumo naranja natural',
    pricePerPerson: 10.00,
    minPersons: 5,
  },
  {
    id: 'coffee-dulce-salado',
    category: 'coffee',
    name: 'Coffee Break Dulce-Salado',
    description: 'Café Colombia Natural, leche, infusiones, 2 bollería mini, 2 sandwiches mini, zumo naranja natural',
    pricePerPerson: 10.50,
    minPersons: 5,
  },
  {
    id: 'coffee-fruta',
    category: 'coffee',
    name: 'Coffee Break Fruta',
    description: 'Café Colombia Natural, leche, infusiones, 2 bollería mini, mera de chocolate negro, brocheta de fruta, zumo naranja natural',
    pricePerPerson: 10.50,
    minPersons: 5,
  },
  {
    id: 'coffee-tentempie',
    category: 'coffee',
    name: 'Coffee Break Tentempié',
    description: 'Café Colombia Natural, leche, infusiones, 2 pastas de té artesanas, 2 sandwiches mini, mini barrita de jamón con tumaca, brocheta de fruta, zumo naranja natural',
    pricePerPerson: 13.00,
    minPersons: 5,
  },
  // Menús
  {
    id: 'menu-almuerzo',
    category: 'menu',
    name: 'Menú Almuerzo',
    description: 'Entrante, plato principal, postre, bebida y café/infusión. Servido en el Café Viena, a 50 metros del hotel. Sujeto a disponibilidad. Lunes a viernes no festivos.',
    pricePerPerson: 16.80,
    minPersons: 10,
    maxPersons: 10,
  },
  {
    id: 'menu-grupos',
    category: 'menu',
    name: 'Menú Grupos',
    description: 'Entrantes al centro, plato principal de carne o pescado, postre e incluye bebida. En el Café Viena, a 50 metros del hotel.',
    pricePerPerson: 30.00,
    minPersons: 10,
  },
],

  eventTypes: [
    'Reunión de equipo',
    'Presentación comercial',
    'Sesión formativa',
    'Convención',
    'Workshop',
    'Otro',
  ],
}